version: '3'
services:
  strapi:
    container_name: strapi
    build: .
    image: strapi/strapi:3.6.8-alpine
    restart: unless-stopped
      #    env_file: .env
    environment:
      DATABASE_CLIENT: strapi
      DATABASE_HOST: strapiDB
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: test
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: development
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
        #      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    networks:
      - strapi
    depends_on:
      - strapiDB

  strapiDB:
    container_name: strapiDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
      #    env_file: .env
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: test
      POSTGRES_DB: strapi
    volumes:
      - data:/var/lib/postgresql/data/ #using a volume

    ports:
      - '5432:5432'
    networks:
      - strapi

volumes:
  data:

networks:
  strapi:
    name: Strapi
    driver: bridge
